package com.razvan.movies.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * MongoDB Data Model Implementation for the Movie Document
 */
@Getter @Setter
@AllArgsConstructor
@NoArgsConstructor
@Document
public class Movie {
    /**
     * Autogenerated Id of the movie
     */
    @Id
    private String id;

    /**
     * Name of the movie
     */
    private String name;

    /**
     * Price of the movie
     */
    private double price;

    /**
     * Length in minutes of the movie
     */
    private int length;

    /**
     * Availability of the movie
     */
    private boolean available;
}
